provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  caire-image-resizer:
    lang: go
    handler: ./caire-openfaas
    image: caire-openfaas:0.1
    environment:
          input_mode: "url"
          output_mode: "image"
          write_timeout: 100s
